Repository Jjanggu-Shrine/Jjan9-Shrine, pull requests merged in 2025-02, with the labels that each got.

#4 ADD workflow
  .github/workflows/run-test.yaml
  src/main/java/com/example/jjangushrine/domain/seller/entity/Seller.java
  src/main/java/com/example/jjangushrine/domain/store/entity/Store.java
Labels: 정우

#8 feat: 장바구니 아이템 생성
  build.gradle
  src/main/java/com/example/jjangushrine/domain/cart/controller/CartController.java
  src/main/java/com/example/jjangushrine/domain/cart/dto/request/CartItemCreateReq.java
  src/main/java/com/example/jjangushrine/domain/cart/dto/response/CartItemCreateRes.java
  src/main/java/com/example/jjangushrine/domain/cart/entity/Cart.java
  src/main/java/com/example/jjangushrine/domain/cart/entity/CartItem.java
  src/main/java/com/example/jjangushrine/domain/cart/repository/CartItemRepository.java
  src/main/java/com/example/jjangushrine/domain/cart/repository/CartRepository.java
  src/main/java/com/example/jjangushrine/domain/cart/service/CartService.java
  src/main/java/com/example/jjangushrine/domain/order/entity/Cart.java
  src/main/java/com/example/jjangushrine/domain/order/entity/Order.java
  src/main/java/com/example/jjangushrine/domain/store/entity/Store.java
  src/main/java/com/example/jjangushrine/exception/GlobalExceptionHandler.java
  src/test/java/com/example/jjangushrine/domain/cart/service/CartServiceTest.java
Labels: 동건

#12 feat: Auth, Security
  .gitignore
  build.gradle
  src/main/java/com/example/jjangushrine/config/security/GenerateJwtSecretKey.java
  src/main/java/com/example/jjangushrine/config/security/SecurityConfig.java
  src/main/java/com/example/jjangushrine/config/security/SecurityConst.java
  src/main/java/com/example/jjangushrine/config/security/entity/CustomUserDetails.java
  src/main/java/com/example/jjangushrine/config/security/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/example/jjangushrine/config/security/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/example/jjangushrine/config/security/jwt/JwtFilter.java
  src/main/java/com/example/jjangushrine/config/security/jwt/JwtUtil.java
  src/main/java/com/example/jjangushrine/config/security/sevice/CustomUserDetailsService.java
  src/main/java/com/example/jjangushrine/domain/auth/controller/AuthController.java
  src/main/java/com/example/jjangushrine/domain/auth/dto/AuthValidation.java
  src/main/java/com/example/jjangushrine/domain/auth/dto/request/AuthReq.java
  src/main/java/com/example/jjangushrine/domain/auth/dto/request/SellerSignUpReq.java
  src/main/java/com/example/jjangushrine/domain/auth/dto/request/SignInReq.java
  src/main/java/com/example/jjangushrine/domain/auth/dto/request/UserSignUpReq.java
  src/main/java/com/example/jjangushrine/domain/auth/dto/response/AuthRes.java
  src/main/java/com/example/jjangushrine/domain/auth/dto/response/SignInRes.java
  src/main/java/com/example/jjangushrine/domain/auth/service/AuthService.java
  src/main/java/com/example/jjangushrine/domain/auth/service/SellerAuthService.java
  src/main/java/com/example/jjangushrine/domain/auth/service/UserAuthService.java
  src/main/java/com/example/jjangushrine/domain/seller/entity/Seller.java
  src/main/java/com/example/jjangushrine/domain/seller/repository/SellerRepository.java
  src/main/java/com/example/jjangushrine/domain/seller/service/SellerService.java
  src/main/java/com/example/jjangushrine/domain/user/dto/UserValidation.java
  src/main/java/com/example/jjangushrine/domain/user/dto/UserValidationMessage.java
  src/main/java/com/example/jjangushrine/domain/user/entity/User.java
  src/main/java/com/example/jjangushrine/domain/user/enums/UserRole.java
  src/main/java/com/example/jjangushrine/domain/user/repository/UserRepository.java
  src/main/java/com/example/jjangushrine/domain/user/service/UserService.java
  src/main/java/com/example/jjangushrine/exception/ErrorCode.java
  src/main/java/com/example/jjangushrine/exception/common/ConflictException.java
  src/main/java/com/example/jjangushrine/exception/common/InvalidException.java
  src/test/java/com/example/jjangushrine/config/TestSecurityConfig.java
  src/test/java/com/example/jjangushrine/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/example/jjangushrine/domain/auth/service/SellerAuthServiceTest.java
  src/test/java/com/example/jjangushrine/domain/auth/service/UserAuthServiceTest.java
  src/test/resources/application.yml
Labels: 예나

#13 refactor: JwtFilter 에러 메시지 반환 방법 변경
  src/main/java/com/example/jjangushrine/config/security/SecurityConfig.java
  src/main/java/com/example/jjangushrine/config/security/jwt/JwtFilter.java
  src/main/java/com/example/jjangushrine/exception/ErrorCode.java
Labels: 예나

#14 refactor: Security 로직 개선
  src/main/java/com/example/jjangushrine/config/security/jwt/JwtFilter.java
  src/main/java/com/example/jjangushrine/config/security/jwt/JwtUtil.java
Labels: 예나

#19 refactor: aws 연동을 위한 시큐리티 주소 추가
  src/main/java/com/example/jjangushrine/config/security/SecurityConfig.java
Labels: 정우

#21 refactor: git action ci add
  .github/workflows/run-test.yaml
Labels: 정우

#28 refactor: CD부분 설정 수정
  .github/workflows/deploy.yaml
Labels: 정우

#38 refactor: JWT subject 지정
  src/main/java/com/example/jjangushrine/config/security/jwt/JwtFilter.java
  src/main/java/com/example/jjangushrine/config/security/jwt/JwtUtil.java
Labels: 예나

#40 refactor: Auth API의 응답 구조를 ApiResponse 형식으로 변경
  src/main/java/com/example/jjangushrine/common/ApiResMessage.java
  src/main/java/com/example/jjangushrine/common/ApiResponse.java
  src/main/java/com/example/jjangushrine/domain/auth/controller/AuthController.java
  src/main/java/com/example/jjangushrine/domain/auth/dto/response/SignInRes.java
Labels: 예나

#35 feat: 장바구니 아이템 추가
  build.gradle
  src/main/java/com/example/jjangushrine/config/RedisConfig.java
  src/main/java/com/example/jjangushrine/domain/cart/controller/CartController.java
  src/main/java/com/example/jjangushrine/domain/cart/dto/request/CartItemCreateReq.java
  src/main/java/com/example/jjangushrine/domain/cart/dto/response/CartItemCreateRes.java
  src/main/java/com/example/jjangushrine/domain/cart/entity/Cart.java
  src/main/java/com/example/jjangushrine/domain/cart/entity/CartItem.java
  src/main/java/com/example/jjangushrine/domain/cart/repository/CartRepository.java
  src/main/java/com/example/jjangushrine/domain/cart/service/CartService.java
  src/main/java/com/example/jjangushrine/exception/ErrorCode.java
  src/main/java/com/example/jjangushrine/exception/GlobalExceptionHandler.java
  src/main/java/com/example/jjangushrine/exception/common/LockException.java
  src/main/java/com/example/jjangushrine/exception/common/Threadxception.java
  src/test/java/com/example/jjangushrine/domain/cart/service/CartServiceTest.java
Labels: 동건

#42 feat: Product 등록 API 구현
  .gitignore
  src/main/java/com/example/jjangushrine/domain/product/controller/ProductController.java
  src/main/java/com/example/jjangushrine/domain/product/dto/request/ProductSaveReq.java
  src/main/java/com/example/jjangushrine/domain/product/dto/response/ProductRes.java
  src/main/java/com/example/jjangushrine/domain/product/entity/Product.java
  src/main/java/com/example/jjangushrine/domain/product/enums/Category.java
  src/main/java/com/example/jjangushrine/domain/product/repository/ProductRepository.java
  src/main/java/com/example/jjangushrine/domain/product/repository/ProductRespositoryImpl.java
  src/main/java/com/example/jjangushrine/domain/product/service/ProductService.java
  src/main/java/com/example/jjangushrine/exception/ErrorCode.java
  src/main/java/com/example/jjangushrine/exception/common/StoreAccessDeniedException.java
  src/test/java/com/example/jjangushrine/domain/product/service/ProductServiceTest.java
Labels: 하영

#45 feat: 어드민 쿠폰 발급
  build.gradle
  src/main/java/com/example/jjangushrine/common/ApiResMessage.java
  src/main/java/com/example/jjangushrine/config/security/SecurityConfig.java
  src/main/java/com/example/jjangushrine/domain/coupon/controller/CouponController.java
  src/main/java/com/example/jjangushrine/domain/coupon/dto/CouponValidationMessage.java
  src/main/java/com/example/jjangushrine/domain/coupon/dto/request/CreateCouponReq.java
  src/main/java/com/example/jjangushrine/domain/coupon/dto/response/CreateCouponRes.java
  src/main/java/com/example/jjangushrine/domain/coupon/repository/CouponRepository.java
  src/main/java/com/example/jjangushrine/domain/coupon/service/CouponService.java
  src/main/java/com/example/jjangushrine/domain/user/enums/UserRole.java
  src/main/java/com/example/jjangushrine/exception/ErrorCode.java
  src/main/java/com/example/jjangushrine/exception/GlobalExceptionHandler.java
  src/main/java/com/example/jjangushrine/exception/coupon/CouponException.java
  src/test/java/com/example/jjangushrine/domain/coupon/service/CouponServiceTest.java
Labels: 정우

#43 feat: 상품 삭제 API
  src/main/java/com/example/jjangushrine/domain/product/controller/ProductController.java
  src/main/java/com/example/jjangushrine/domain/product/dto/request/ProductSaveReq.java
  src/main/java/com/example/jjangushrine/domain/product/dto/response/ProductSaveRes.java
  src/main/java/com/example/jjangushrine/domain/product/entity/Product.java
  src/main/java/com/example/jjangushrine/domain/product/exception/ProductAccessDeniedException.java
  src/main/java/com/example/jjangushrine/domain/product/exception/ProductNotFoundException.java
  src/main/java/com/example/jjangushrine/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/com/example/jjangushrine/domain/product/repository/ProductRespositoryImpl.java
  src/main/java/com/example/jjangushrine/domain/product/service/ProductService.java
  src/main/java/com/example/jjangushrine/exception/ErrorCode.java
  src/test/java/com/example/jjangushrine/domain/product/service/ProductServiceTest.java
Labels: 하영

#46 feat: 장바구니 아이템 수량 변경
  src/main/java/com/example/jjangushrine/config/RedisConfig.java
  src/main/java/com/example/jjangushrine/domain/cart/controller/CartController.java
  src/main/java/com/example/jjangushrine/domain/cart/dto/request/CartItemUpdateReq.java
  src/main/java/com/example/jjangushrine/domain/cart/service/CartService.java
Labels: 동건

#56 feat: User Api
  src/main/java/com/example/jjangushrine/common/ApiResMessage.java
  src/main/java/com/example/jjangushrine/domain/address/repository/AddressRepository.java
  src/main/java/com/example/jjangushrine/domain/address/service/AddressService.java
  src/main/java/com/example/jjangushrine/domain/user/controller/UserController.java
  src/main/java/com/example/jjangushrine/domain/user/dto/request/UserUpdateInfoReq.java
  src/main/java/com/example/jjangushrine/domain/user/dto/request/UserUpdateReq.java
  src/main/java/com/example/jjangushrine/domain/user/dto/response/UserReadInfoRes.java
  src/main/java/com/example/jjangushrine/domain/user/dto/response/UserRes.java
  src/main/java/com/example/jjangushrine/domain/user/entity/User.java
  src/main/java/com/example/jjangushrine/domain/user/repository/UserRepository.java
  src/main/java/com/example/jjangushrine/domain/user/service/UserService.java
Labels: 예나

#59 feat: 쇼핑몰 등록 기능 추가
  src/main/java/com/example/jjangushrine/common/ApiResMessage.java
  src/main/java/com/example/jjangushrine/domain/store/controller/StoreController.java
  src/main/java/com/example/jjangushrine/domain/store/dto/StoreValidationMessage.java
  src/main/java/com/example/jjangushrine/domain/store/dto/request/StoreCreateReq.java
  src/main/java/com/example/jjangushrine/domain/store/entity/Store.java
  src/main/java/com/example/jjangushrine/domain/store/service/StoreService.java
Labels: 예나

#61 feat: 쇼핑몰 조회 기능 추가
  src/main/java/com/example/jjangushrine/domain/store/controller/StoreController.java
  src/main/java/com/example/jjangushrine/domain/store/dto/response/StoreRes.java
  src/main/java/com/example/jjangushrine/domain/store/repository/StoreRepository.java
  src/main/java/com/example/jjangushrine/domain/store/service/StoreService.java
Labels: 예나

#64 refactor: Product에서 사용할 findSellerByEmail 메서드 추가
  src/main/java/com/example/jjangushrine/domain/seller/repository/SellerRepository.java
  src/main/java/com/example/jjangushrine/domain/seller/service/SellerService.java
  src/main/java/com/example/jjangushrine/exception/auth/ForbiddenException.java
  src/main/java/com/example/jjangushrine/exception/auth/LoginFailedException.java
  src/main/java/com/example/jjangushrine/exception/auth/UnauthorizedException.java
  src/main/java/com/example/jjangushrine/exception/auth/WrongCredentialsException.java
  src/main/java/com/example/jjangushrine/exception/common/ForbiddenException.java
  src/main/java/com/example/jjangushrine/exception/common/MenuNotFoundException.java
  src/main/java/com/example/jjangushrine/exception/common/OrderNoDeivered.java
  src/main/java/com/example/jjangushrine/exception/common/OrderNotFoundException.java
  src/main/java/com/example/jjangushrine/exception/common/SecurityAccessDeniedException.java
  src/main/java/com/example/jjangushrine/exception/validation/DuplicateEmailException.java
  src/main/java/com/example/jjangushrine/exception/validation/DuplicateUsernameException.java
  src/main/java/com/example/jjangushrine/exception/validation/WrongAccessException.java
Labels: 예나

#66 feat: 주문생성 (동시성 미적용)
  src/main/java/com/example/jjangushrine/domain/cart/dto/request/CartItemCreateReq.java
  src/main/java/com/example/jjangushrine/domain/cart/dto/request/CartItemUpdateReq.java
  src/main/java/com/example/jjangushrine/domain/cart/dto/response/CartItemCreateRes.java
  src/main/java/com/example/jjangushrine/domain/cart/entity/Cart.java
  src/main/java/com/example/jjangushrine/domain/cart/entity/CartItem.java
  src/main/java/com/example/jjangushrine/domain/cart/service/CartService.java
  src/main/java/com/example/jjangushrine/domain/coupon/entity/UserCoupon.java
  src/main/java/com/example/jjangushrine/domain/coupon/repository/UserCouponRepository.java
  src/main/java/com/example/jjangushrine/domain/order/controller/OrderController.java
  src/main/java/com/example/jjangushrine/domain/order/dto/response/OrderItemRes.java
  src/main/java/com/example/jjangushrine/domain/order/dto/response/OrderRes.java
  src/main/java/com/example/jjangushrine/domain/order/entity/Order.java
  src/main/java/com/example/jjangushrine/domain/order/entity/OrderItem.java
  src/main/java/com/example/jjangushrine/domain/order/repository/OrderItemRepository.java
  src/main/java/com/example/jjangushrine/domain/order/repository/OrderRepository.java
  src/main/java/com/example/jjangushrine/domain/order/service/OrderService.java
  src/main/java/com/example/jjangushrine/domain/product/entity/Product.java
  src/main/java/com/example/jjangushrine/domain/product/service/ProductService.java
  src/main/java/com/example/jjangushrine/exception/ErrorCode.java
  src/main/java/com/example/jjangushrine/exception/common/ProductOutOfStock.java
Labels: 동건

#67 feat : 주문 취소 기능 구현
  src/main/java/com/example/jjangushrine/domain/cart/dto/response/CartItemCreateRes.java
  src/main/java/com/example/jjangushrine/domain/cart/service/CartService.java
  src/main/java/com/example/jjangushrine/domain/coupon/entity/UserCoupon.java
  src/main/java/com/example/jjangushrine/domain/coupon/repository/UserCouponRepository.java
  src/main/java/com/example/jjangushrine/domain/order/controller/OrderController.java
  src/main/java/com/example/jjangushrine/domain/order/entity/Order.java
  src/main/java/com/example/jjangushrine/domain/order/repository/OrderItemRepository.java
  src/main/java/com/example/jjangushrine/domain/order/service/OrderService.java
  src/main/java/com/example/jjangushrine/domain/product/dto/response/ProductRes.java
  src/main/java/com/example/jjangushrine/domain/product/entity/Product.java
  src/main/java/com/example/jjangushrine/domain/product/service/ProductService.java
  src/main/java/com/example/jjangushrine/exception/ErrorCode.java
  src/main/java/com/example/jjangushrine/exception/common/OrderException.java
Labels: 동건

#72 Feat/usergetcoupon
  src/main/java/com/example/jjangushrine/common/ApiResMessage.java
  src/main/java/com/example/jjangushrine/domain/coupon/controller/UserCouponController.java
  src/main/java/com/example/jjangushrine/domain/coupon/dto/response/UserCouponListRes.java
  src/main/java/com/example/jjangushrine/domain/coupon/repository/UserCouponRepository.java
  src/main/java/com/example/jjangushrine/domain/coupon/service/UserCouponService.java
Labels: 정우

#71 feat: Product 조회 API
  src/main/java/com/example/jjangushrine/domain/product/controller/ProductController.java
  src/main/java/com/example/jjangushrine/domain/product/entity/Product.java
  src/main/java/com/example/jjangushrine/domain/product/exception/ProductAccessDeniedException.java
  src/main/java/com/example/jjangushrine/domain/product/exception/ProductNotFoundException.java
  src/main/java/com/example/jjangushrine/domain/product/repository/ProductRepositoryCustom.java
  src/main/java/com/example/jjangushrine/domain/product/repository/ProductRepositoryImpl.java
  src/main/java/com/example/jjangushrine/domain/product/service/ProductService.java
  src/main/java/com/example/jjangushrine/exception/common/AccessDeniedException.java
  src/main/java/com/example/jjangushrine/exception/common/StoreAccessDeniedException.java
Labels: 하영

#73 fix : 동시성 제어 구현
  src/main/java/com/example/jjangushrine/domain/cart/service/CartService.java
  src/main/java/com/example/jjangushrine/domain/coupon/repository/UserCouponRepository.java
  src/main/java/com/example/jjangushrine/domain/order/service/OrderService.java
  src/main/java/com/example/jjangushrine/domain/product/entity/Product.java
  src/main/java/com/example/jjangushrine/domain/product/repository/ProductRepository.java
  src/main/java/com/example/jjangushrine/domain/product/service/ProductService.java
  src/test/java/com/example/jjangushrine/domain/cart/service/CartServiceTest.java
  src/test/java/com/example/jjangushrine/domain/product/service/ProductIssueServiceTest.java
  src/test/java/com/example/jjangushrine/domain/product/service/ProductServiceTest.java
Labels: 동건

#79 feat: 인기 상품 순위 조회 API
  src/main/java/com/example/jjangushrine/config/RedisConfig.java
  src/main/java/com/example/jjangushrine/domain/product/controller/ProductController.java
  src/main/java/com/example/jjangushrine/domain/product/dto/ProductValidationMessage.java
  src/main/java/com/example/jjangushrine/domain/product/dto/request/ProductSaveReq.java
  src/main/java/com/example/jjangushrine/domain/product/repository/ProductRepository.java
  src/main/java/com/example/jjangushrine/domain/product/service/ProductService.java
  src/main/java/com/example/jjangushrine/domain/rank/controller/ProductRankController.java
  src/main/java/com/example/jjangushrine/domain/rank/dto/response/ProductRankRes.java
  src/main/java/com/example/jjangushrine/domain/rank/service/ProductRankService.java
  src/test/java/com/example/jjangushrine/domain/product/service/ProductServiceTest.java
Labels: 하영

#90 docs: 시스템 아키텍쳐 추가 및 수정
  README.md
Labels: 하영

#93 fix: 상품 랭킹 담는 Sorted Set TTL 수정
  src/main/java/com/example/jjangushrine/domain/rank/service/ProductRankService.java
Labels: 하영
